### ISSUE TITLE
Typography / rhythm / spacing issues

### ISSUE THREAD

**Issue by robotpony** [lemonstand/lscloud-theme-happyhour#1]
## H1 to P hierarchy off

![H1 to P](https://www.evernote.com/l/AQpKaBTPZOZOxaI07WqLIFVFsZhGb3Y57MUB/image.png)

Distance above a heading (`a`) should be greater than the distance below (`b`). Here the distance above is less.

The distance between text suggests _hierarchy_, as in how the text relates to the next text. The closer it is, the more related it is. Here, its mistakenly saying that the heading is more related to the above content.

Instead, the space below and above should be inverted. Commonly, the spacing is more like `1.5:1` or `2:1` (or more).

**Comment by robotpony** [comment]
## Header alignment is off

![Header alignment](https://www.evernote.com/l/AQpcl5_L8p1FhpZ0EAJEvX0q26d7He0gUA8B/image.png)
1. Main title text is off by 2-3 pixel (from grid)
2. Search icon size/position is off in search input control
3. Menu text should probably be sized to middle grid

**Comment by robotpony** [comment]
## Text colour issues

![](https://www.evernote.com/l/AQp4w7uXuhBA67zJtdECibkQ0HmnToFKD9sB/image.png)

`#4a4a4a` is the _dark_ color, so `#000000` should not be used (it looks off).

**Comment by robotpony** [comment]
## Rhythm issues

![Rhythm](https://www.evernote.com/l/AQpRPIR3Jr1MpKvYJxJqZ07lpNBbIND3pgAB/image.png)

Notice the text spacing is large. Remember that `more space == less related`.
1. The H1 line height is 150% (or so), makes each heading line look disconnected.  This should be less.
2. The after-H1 height is almost equal to the line height space (should be more)
3. Space between meta-data isn't enough, as they don't stand out enough from each other.
4. Spacing to price is too much (makes it feel disconnected)

**Comment by robotpony** [comment]
@tomcornall Additional tweaks needed.

**Comment by tomcornall** [comment]
Thanks for the feedback guys!
Ref To Do:
- [x] Breadcrumbs on product page is too dark / too much contrast. It takes away from the product title.
- [x] Some blue links do not have any change on :hover. Example, “write review” link on product page, “how does it work?” link on homepage hero (maybe others)
- [x] I like the LS symbol in footer, but I think since it’s more of a production theme it should be removed (but leave the link), so that customers have less work before going live 
- [x] Having product images on the right feels so weird to me. I guess I am just so used to it being on the left that it’s become an expectation. Please swap the images and price, title and description  
  *when you do this, the breadcrumbs may need some space added between them and the product image. Feel free to post a screenshot so we can double check
- [x] Once you add a product to cart, you can’t add anymore, unless you refresh the page
- [x] Category List
- [x] :hover on product images in grid view should be more obvious. Maybe a subtle opacity change
- [x] Change text for “Copy Billing info to Shipping” to “Use billing info for shipping” and have this selected by default (test that it works for with guest, and a logged in customer that has a previous address saved w/ different shipping + billing)
- [x] Another one of those blue links that needs :hover is the “remove” link on /cart

**Comment by tomcornall** [comment]
Additional: 
- [ ] Update logos to jpeg
- [ ]
